export const CATEGORIAS_CONFIG = {
  categorias_validas: [
    "ALIMENTACAO (OPERACAO)",
    "ALIMENTACAO (DIRETORIA)",
    "ALIMENTACAO (ADMINISTRATIVO)",
    "COMBUSTIVEIS",
    "MERCADO",
    "PEDAGIOS",
    "DESPESAS A IDENTIFICAR",
    "MATERIAIS APLICADOS NA PRESTACAO DE SERVICOS",
    "MANUTENCAO DE VEICULOS",
    "TELEFONIA E INTERNET",
    "SEGUROS DE VEICULOS",
    "ESTACIONAMENTOS",
    "SOFTWARES ADMINISTRATIVOS",
    "SOFTWARES DE ENGENHARIA / OPERACIONAL",
    "CURSOS E TREINAMENTOS OPERACIONAIS",
    "EQUIPAMENTOS DE INFORMÁTICA",
    "FERRAMENTAS",
    "UNIFORMES E EPIS"
  ],
  categoria_padrao: "DESPESAS A IDENTIFICAR",
  conta_corrente: "CARTAO DE CREDITO",
  fornecedor_categoria: {
    "GRACIOSA": "ALIMENTACAO (OPERACAO)",
    "TIBAGI": "ALIMENTACAO (OPERACAO)",
    "CONDOR": "ALIMENTACAO (OPERACAO)",
    "CANTINHO DO PAO": "ALIMENTACAO (OPERACAO)",
    "DONA CHEFFA": "ALIMENTACAO (OPERACAO)",
    "ALE LANCHES": "ALIMENTACAO (OPERACAO)",
    "DOS HERMANOS": "ALIMENTACAO (OPERACAO)",
    "BATEL GRILL": "ALIMENTACAO (OPERACAO)",
    "PRENSADO": "ALIMENTACAO (OPERACAO)",
    "LANCHONETE": "ALIMENTACAO (OPERACAO)",
    "LANCHES": "ALIMENTACAO (OPERACAO)",
    "BUFFALO RANCH": "ALIMENTACAO (DIRETORIA)",
    "CAMPODORO": "ALIMENTACAO (DIRETORIA)",
    "CHURRASCARIA DOS AMI": "ALIMENTACAO (DIRETORIA)",
    "MADALOSSO": "ALIMENTACAO (DIRETORIA)",
    "MERCADO": "MERCADO",
    "SUPERMERCADO": "MERCADO",
    "DELICAT": "MERCADO",
    "HIPERMERCADO": "MERCADO",
    "POSTO": "COMBUSTIVEIS",
    "HULK": "COMBUSTIVEIS",
    "TRANSCAP": "COMBUSTIVEIS",
    "COMBUSTIVEL": "COMBUSTIVEIS",
    "SHELL": "COMBUSTIVEIS",
    "IPIRANGA": "COMBUSTIVEIS",
    "PEDAGIO": "PEDAGIOS",
    "CONCESSIONARIA DE RO": "PEDAGIOS",
    "EPR LITORAL": "PEDAGIOS",
    "ECOVIA": "PEDAGIOS",
    "RODONORTE": "PEDAGIOS",
    "ARTERIS": "PEDAGIOS",
    "BORRACHARIA": "MANUTENCAO DE VEICULOS",
    "FORMULA RENAULT": "MANUTENCAO DE VEICULOS",
    "MECANICA": "MANUTENCAO DE VEICULOS",
    "PNEU": "MANUTENCAO DE VEICULOS",
    "LAVA CAR": "MANUTENCAO DE VEICULOS",
    "AUTO CENTER": "MANUTENCAO DE VEICULOS",
    "CLARO": "TELEFONIA E INTERNET",
    "VIVO": "TELEFONIA E INTERNET",
    "TIM": "TELEFONIA E INTERNET",
    "OI MOVEL": "TELEFONIA E INTERNET",
    "KENNEDY": "FERRAMENTAS",
    "CEFEQ": "FERRAMENTAS",
    "FERRAGISTA": "FERRAMENTAS",
    "CARVALHO MAT": "MATERIAIS APLICADOS NA PRESTACAO DE SERVICOS",
    "MAT CONSTR": "MATERIAIS APLICADOS NA PRESTACAO DE SERVICOS",
    "ELETRICA": "MATERIAIS APLICADOS NA PRESTACAO DE SERVICOS",
    "HIDRAULICA": "MATERIAIS APLICADOS NA PRESTACAO DE SERVICOS",
    "TERA ELETRICA": "MATERIAIS APLICADOS NA PRESTACAO DE SERVICOS",
    "ATLANTICO": "UNIFORMES E EPIS",
    "EPI": "UNIFORMES E EPIS",
    "ALTO QI": "SOFTWARES DE ENGENHARIA / OPERACIONAL",
    "AUTODESK": "SOFTWARES DE ENGENHARIA / OPERACIONAL",
    "CEFIS": "CURSOS E TREINAMENTOS OPERACIONAIS",
    "PORTO SEGURO": "SEGUROS DE VEICULOS",
    "ESTACIONAMENTO": "ESTACIONAMENTOS",
    "PARK": "ESTACIONAMENTOS"
  } as Record<string, string>,
  titular_departamento: {
    "CONRADO": "DIRETORIA",
    "DEFAULT": "OPERACAO"
  } as Record<string, string>
};

export function suggestCategoria(descricao: string): string {
  if (!descricao) return CATEGORIAS_CONFIG.categoria_padrao;
  const descUpper = descricao.toUpperCase().trim();

  for (const [chave, categoria] of Object.entries(CATEGORIAS_CONFIG.fornecedor_categoria)) {
    if (descUpper.includes(chave.toUpperCase())) {
      return categoria;
    }
  }

  return CATEGORIAS_CONFIG.categoria_padrao;
}
